### PR TITLE
fix #25

### LINKED ISSUE #25: django-cms apphooks are not displayed in javascript resolver
[see info on apphooks.](http://docs.django-cms.org/en/latest/extending_cms/app_integration.html#app-hooks)

to reproduce it you could use my test project: https://github.com/szelga/js-cms-test

on page http://127.0.0.1:8000/admin/cms/page/ create root page with some content, and, say, page with slug 'test2' hooked with 'My App' application (advanced settings tab). make sure that pages are published and you also clicked "publish draft" button. then test it.

on page http://localhost:8000/djangojs/init.js hooked app is not displayed, and it should be something like

``` javascript
"myapp-view": "/test2/",
```

### PR DESCRIPTION
**Pull request by szelga**
fixes issue #25 by specifically checking if we use django-cms' AppRegexURLResolver.

### CODE REVIEW

**Comment by noirbizarre** [comment]
You need to make your code PEP8 compliant according to project guidelines:

``` console
$ make pep8
```

Rebase it on the master if your missing some parts.

Can you in the same time, merge both commit into one (to have a clean diff).

I'll merge it once it's done.

Next time, when you want to submit a bug report and the corresponding fix, just open a pull request: an issue will be automatically created and its easier to track and understand.

By the way, thanks for the fix.

**Comment by szelga** [comment]
i'm fairly inexperienced with git, so merging the commits and pushing them didn't go so well, sorry. anyway, here's the commit: https://github.com/szelga/django.js/commit/179876f53674b482fccdd509e72012b152d48e17

**Comment by noirbizarre** [comment]
For the next time,

When you submit a pul request based on a branch, you can update the branch (even with a `git push -`f) et the pull request will automatically update itself.

To rebase your branch properly on master and merge some commit together, you need to use the interactive rebase.
In you case, you could have done:

``` console
$ git remote add noirbizarre https://github.com/noirbizarre/django.js.git
$ git pull noirbizarre master  # sync your master from upstream
$ git checkout fix_cms
$ git rebase -i master  # start the interactive rebase
```

You would have this displayed:

```
pick 6bd6c6b fix #25
pick 89b3e86 fix #25 -- fix prev commit
```

To amend the first commit with the second, you should have written:

```
pick 6bd6c6b fix #25
fixup 89b3e86 fix #25 -- fix prev commit
```

or 

```
pick 6bd6c6b fix #25
f 89b3e86 fix #25 -- fix prev commit
```

Once it's done, you could have overwritten your remote branch and updated the pull-request:

``` console
$ git push -f
```

**Comment by szelga** [comment]
thank you very much and sorry for inconvenience.

i'm used to mercurial and some of its features and workflow are new to me, so your tips are very helpful.

**Comment by noirbizarre** [comment]
You are very welcome!
There was no inconvenience, don't worry !

I'm glad to help on git usage.
I think I would be lost on mercurial too!!

Using mercurial, you are not so far from git, just some tips like that to learn!

**Pull request closed without merging**
